version: 2

updates:
  - package-ecosystem: docker
    directory: "/"
    labels: [Dependencies]
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: "/"
    labels: [Dependencies]
    schedule:
      interval: monthly
