name: Tests

on: [pull_request_target]

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image
        run: make build
